name: Check Latex Compilation

on:
  push:
    paths-ignore:
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main_cv.tex

      - name: Publish PDF
        uses: appleboy/scp-action@v0.1.7
        with:
          name: PDF
          path: main_cv.pdf
